### ISSUE TITLE
Allow sink to a table with a different name than the source topic

### ISSUE THREAD

**Issue by abdelhakimbendjabeur** [ClickHouse/clickhouse-kafka-connect#54] opened 2023-02-07 11:08 UTC
Hello, 

As it is mentioned in [Target Tables section the docs](https://clickhouse.com/docs/en/integrations/kafka/clickhouse-kafka-connect-sink/#target-tables), the table name must match the topic name. This can be a problem when we have a naming convention for topics (in which we may find dots and hyphens, e.g. `foo.bar.table-name`

One improvement I can suggest is to add a mapping that will match the topic name with the target table name
```
target.tables.mapping="foo.bar.table-name:foo_bar_table_name;topic-one:topic_one;..."
```
Thank you

**Comment by mzitnik** [comment] 2023-02-10 11:24
Duplicate of #50

**Closed** 2023-02-10 11:25 UTC
